### ISSUE TITLE
Constraint dropdown is not filled on eucp-project.github.io/atlas/

### ISSUE THREAD

**Issue by sverhoeven** [eucp-project/atlas#52]
Running locally on wtih `npm run dev` shows the constraint dropdown like
![localhost_3000_atlas_](https://user-images.githubusercontent.com/1713488/140032807-6b3ff729-46c0-490d-a51f-14a3a9b9e0ae.png)
 
However on https://eucp-project.github.io/atlas/ the contraint dropdown is empty, see
![eucp-project github io_atlas_](https://user-images.githubusercontent.com/1713488/140032980-c9c5bd4f-e464-4717-8723-3cf70259e866.png)
The plot shown is constraint.

**Comment by sverhoeven** [comment]
Running generated version locally also gives same problem
```
npm run generate
mv dist/ atlas
python3 -m http.server 8000 
# Goto http://0.0.0.0:8000/atlas/
```

**Comment by Peter9192** [comment]
I fixed this yesterday. The problem was that I deduced the settings from the filename, so "..../.../...cons.jpg" was used to set the initial value for constrained/unconstrained. But because of this hash addition that you told me about, indexing the last part of this string resulted in something different after `nuxt generate`. I pushed the fix directly to master...
